- name: 生成发布标签
  id: tag
  if: steps.organize.outcome == 'success' && env.UPLOAD_RELEASE == 'true'
  run: |
    echo -e "🎉 x86平台\n✅ OpenWrt主线源码\n📦 x86固件\n❗️ 固件由GitHub Actions自动编译" >> release.txt
    echo "release_tag=$(date +"%Y.%m.%d_x86")" >> $GITHUB_OUTPUT
    echo "status=success" >> $GITHUB_OUTPUT

- name: 上传固件到发布
  uses: softprops/action-gh-release@master
  if: steps.tag.outputs.status == 'success' && !cancelled()
  with:
    tag_name: ${{ steps.tag.outputs.release_tag }}
    body_path: release.txt
    files: ${{ env.FIRMWARE }}/*
